[project]
name = "record-voice-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools>=80.9.0",
]

[tool.uv]
no-build-isolation-package = ['pkuseg']
